### ISSUE TITLE
Maintainer Needed.

### ISSUE THREAD

**Issue by alanpeabody** [alanpeabody/resque-job-stats#22]
I am no longer using Resque or this library. I am happy to hand of maintenance to anyone who is actively using this.

**Comment by lukeasrodgers** [comment]
@alanpeabody we are using this in production, and have merged #9 into our own branch (https://github.com/Headlinerfm/resque-job-stats/tree/copromote).

I'd be happy to help with maintenance, if you are still interested. I wouldn't be able to dedicate a ton of time to it, but I could do a couple hours a month.

**Comment by alanpeabody** [comment]
Thanks @lukeasrodgers, I most definitly am. I am happy to transfer the repo or add you as a collaborator... your choice.

**Comment by lukeasrodgers** [comment]
@alanpeabody how about just adding me as a collaborator, and if things go fine for a while, maybe we can transfer ownership.

Would you prefer to be @-mentioned or otherwise included on PR/issues, or not? Or only on major changes? Any level of involvement is fine obviously, just let me know what works for you.
cheers

**Comment by alanpeabody** [comment]
@lukeasrodgers honestly I am looking to be totally hands off as I don't use this gem, Resque, or even Ruby much any more. I will probably read PRs, but won't have any input as long as things seem to be going smoothly.

**Comment by lukeasrodgers** [comment]
Sounds good.

**Comment by lukeasrodgers** [comment]
@alanpeabody could you give me push access to rubygems.org? I'd like to release 0.4.0 but am unable to do so. Also if you could give me rights to add/create labels for issues and PRs that would be helpful. thanks

**Comment by alanpeabody** [comment]
@lukeasrodgers I don't know how to do the later, I don't see any options in collaborators?

You should be added to the gem on rubygems.org.

**Comment by lukeasrodgers** [comment]
@alanpeabody okay, I have rubygems.org access, thanks. Re: issues/tagging, not a big deal at the moment.
