### ISSUE TITLE
reset histories to 0?

### ISSUE THREAD

**Issue by chrishough** [alanpeabody/resque-job-stats#29]
How do we reset the history to 0?

**Comment by lukeasrodgers** [comment]
Hi @chrishough sorry for the late reply -- I'm not getting notices for new issues. I suspect you've already solved the problem, but in case you haven't: this gem doesn't currently provide a way to reset histories, you'd have to do it manually for each redis key matching the pattern `"stats:jobs:#{self.name}:history"` (see https://github.com/alanpeabody/resque-job-stats/blob/bd95e193cdb1bfac6d3b84975705638459a9f2a2/lib/resque/plugins/job_stats/history.rb#L12)

**Comment by chrishough** [comment]
No worries @lukeasrodgers : I did end up finding out how to manually reset them all in redis.
