### ISSUE TITLE
Warning from Resque about Resque::Helpers

### ISSUE THREAD

**Issue by jagshub** [alanpeabody/resque-job-stats#30]
Hey there,

Will this be addressed soon?
I see the warning and iam using resque 1.25.2 currently.
Resque::Helpers will be gone with no replacement in Resque 2.0.0

Thanks
Jag

**Comment by lukeasrodgers** [comment]
Hi @jagshub sorry for the late reply -- I'm not getting notices for new issues. My understanding is that resque 2 is not going to happen (or at least is not in the works at the moment), see https://github.com/resque/resque/issues/1170

If you upgrade to a newer version of resque 1.x, the warning messages will be gone (see https://github.com/resque/resque/pull/1376).
