### ISSUE TITLE
require 'resque-job-stats/server' for web UI

### ISSUE THREAD

**Issue by thenashfactor** [alanpeabody/resque-job-stats#31]
Where should this be required in a Rails app?

**Comment by lukeasrodgers** [comment]
Hi @thenashfactor, sorry for the late reply -- I'm not getting notices for new issues. I assume you've figure this out already, but in case not, you can put this in an initializer for resque which you probably already have, or one specifically for this gem, e.g. `config/initializers/resque-jobs-stats.rb`.
